### ISSUE TITLE
File ~vue3-q-tel-input/dist/vue3-q-tel-input.esm.css doesnt exist

### ISSUE THREAD

**Issue by kamasuPaul** [CdTgr/vue3-q-tel-input#13] opened 2022-10-15 05:31 UTC
When importing the CSS the file `vue3-q-tel-input.esm.css` doesn't exist in the directory after installing with yarn

**Comment by kamasuPaul** [comment] 2022-10-15 05:35
![Screenshot 2022-10-15 083331](https://user-images.githubusercontent.com/35300826/195970719-382b2f32-a697-4c33-971a-578e49d3b276.png)
Then this error shows up even when the phone number is correct

**Comment by RizaHKhan** [comment] 2022-10-15 16:59
Duplicate of https://github.com/CdTgr/vue3-q-tel-input/issues/12 but the error still persists

**Comment by CdTgr** [comment] 2022-10-28 04:56
Should be resolved in version [1.0.23](https://www.npmjs.com/package/vue3-q-tel-input/v/1.0.23)

**Closed by CdTgr** 2022-10-28 04:56 UTC
