### ISSUE TITLE
US default-country reverts to  Canada flag when enter number

### ISSUE THREAD

**Issue by andyslack** [CdTgr/vue3-q-tel-input#23] opened 2023-02-22 19:15 UTC
Hi @CdTgr 

Firstly, thank you so much for building and maintaining this plugin and for making it open source.

I did submit a pull request to make the search icon dynamic as my projects use Font Awesome and not the out of the box Quasar icon pack.

However I spotted another issue.

When I specify a default country e.g `us` when type the number, the flag reverts to Canada for some reason

Any ideas on how we can stop that happening?

![onload](https://user-images.githubusercontent.com/3747768/220735029-6426fe0e-bfb1-4629-b4ae-ec8d8ef5aecc.png)

![adding_number](https://user-images.githubusercontent.com/3747768/220735066-e26813b9-74f5-46c1-8f70-9419f0edbb6e.png)

**Comment by CdTgr** [comment] 2023-02-23 17:43
@andyslack Thank you for submitting the issue. Looks like its a reproducible bug. I will look into the case and fix it asap!

**Comment by CdTgr** [comment] 2023-02-25 13:46
The issue is resolved in [v1.1.0](https://www.npmjs.com/package/vue3-q-tel-input/v/1.1.0)

**Closed by CdTgr** 2023-02-25 13:46 UTC
Labels: bug
